name: cw
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

  # Core UI
  cupertino_icons: ^1.0.8

  # Firebase packages (for Dart 3.7.2 / Flutter 3.22)
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_database: ^11.3.7


  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^5.0.0
fl_chart: ^1.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/profile.png
    - assets/chart_placeholder.png
    - assets/container.png
