// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhU1uy1czDSGfjFqSS2TKpeQoKkiwOtc0',
    appId: '1:482731147534:web:f40ef293ef46bf501bd75f',
    messagingSenderId: '482731147534',
    projectId: 'smartjarcup',
    authDomain: 'smartjarcup.firebaseapp.com',
    databaseURL: 'https://smartjarcup-default-rtdb.firebaseio.com',
    storageBucket: 'smartjarcup.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCso8hR5fl1xDTH2VstWNkgW16_NJqwvHk',
    appId: '1:482731147534:android:fc4710bf3b991c1a1bd75f',
    messagingSenderId: '482731147534',
    projectId: 'smartjarcup',
    databaseURL: 'https://smartjarcup-default-rtdb.firebaseio.com',
    storageBucket: 'smartjarcup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5usEG1RTtrSdvJ5HRP3hHj4aHH356qsk',
    appId: '1:482731147534:ios:56134ab769d344631bd75f',
    messagingSenderId: '482731147534',
    projectId: 'smartjarcup',
    databaseURL: 'https://smartjarcup-default-rtdb.firebaseio.com',
    storageBucket: 'smartjarcup.firebasestorage.app',
    iosBundleId: 'com.example.cw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5usEG1RTtrSdvJ5HRP3hHj4aHH356qsk',
    appId: '1:482731147534:ios:56134ab769d344631bd75f',
    messagingSenderId: '482731147534',
    projectId: 'smartjarcup',
    databaseURL: 'https://smartjarcup-default-rtdb.firebaseio.com',
    storageBucket: 'smartjarcup.firebasestorage.app',
    iosBundleId: 'com.example.cw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhU1uy1czDSGfjFqSS2TKpeQoKkiwOtc0',
    appId: '1:482731147534:web:f44d9783246ed9ef1bd75f',
    messagingSenderId: '482731147534',
    projectId: 'smartjarcup',
    authDomain: 'smartjarcup.firebaseapp.com',
    databaseURL: 'https://smartjarcup-default-rtdb.firebaseio.com',
    storageBucket: 'smartjarcup.firebasestorage.app',
  );

}